import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Twitter Clone App</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://www.freepnglogos.com/uploads/twitter-logo-png/twitter-logo-vector-png-clipart-1.png"
        />
      </Head>
    </div>
  );
}
